// <auto-generated />
namespace UniQode.Data.Migrations.SecondaryModel
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixEmployeesAndExternalRefs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixEmployeesAndExternalRefs));
        
        string IMigrationMetadata.Id
        {
            get { return "201606281336392_FixEmployeesAndExternalRefs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
